### ISSUE TITLE
unable to flash firmware built with binaries-marvell-armada-SDK10.0.1.0 branch

### ISSUE THREAD

**Issue by bunder2015** [MarvellEmbeddedProcessors/binaries-marvell#4]
```
=> bubt flash-image.bin spi mmc
Burning U-Boot image "flash-image.bin" from "mmc" to "spi"
ERROR: Bad MAGIC 0xd2810600 != 0xb105b002
Error: Image header verification failed
```
I can flash firmware built with binaries-marvell-armada-18.12 however.

I'm using the mcbin double if it helps.

ARM-software/arm-trusted-firmware@08532d7
MarvellEmbeddedProcessors/mv-ddr-marvell@7c35173
u-boot/u-boot@1b8ad81

Thanks

**Comment by kostapr** [comment]
You should be able to test your flash image format on your build machine by running "doimage -p flash-image.bin"

**Comment by bunder2015** [comment]
I tried it again and it seems to be working now.  Not sure why it didn't last week.  Thanks for getting back to me and sorry for the delay.
